MAIN_COLUMNS = [
    'order_code',
    'created_by',
    'service_order_no',
    'service_number',
    'customer',
    'order_type',
    'order_status',
    'taken_date',
    'current_crd',
    'initial_crd',
    'assignee',
    'pm_nonpm',
    'project_code',
    'circuit_code',
    'product_code',
    'product_description',
    'business_sector',
    'exchange_code_a',
    'exchange_code_b',
    'brn',
    'sde_received_date',
    'arbor_service',
    'service_type',
    'order_priority',
    'parameter_value',
    'department',
    'group_id',
    'step_no',
    'activity_name',
    'due_date',
    'status',
    'ready_date',
    'completed_date',
    'act_dly_reason_date',
    'act_delay_reason'
]

CRD_AMENDMENT_COLUMNS = [
    'order_code',
    'note_code',
    'crd_amendment_date',
    'old_crd',
    'new_crd',
    'crd_amendment_reason',
    'crd_amendment_reason_gsp'
    # 'crd_amendment_details'
]

MAIN_NPP_COLUMNS = [
    'order_code',
    'created_by',
    'service_order_no',
    'service_number',
    'customer',
    'order_type',
    'order_status',
    'taken_date',
    'current_crd',
    'initial_crd',
    'close_date',
    'assignee',
    'project_code',
    'circuit_code',
    'npp_level',
    'product_code',
    'product_description',
    'AELineCeaseDt',
    'AELineCurrencyCd',
    'AELineMRC',
    'AELineOTC',
    'AELinePartnerContractStartDt',
    'AELinePartnerContractTerm',
    'AELinePartnerNm',
    'AELineSTPO',
    'AELineTax',
    'AELineTPTy',
    'APartnerCctRef',
    'BOLLCBCurrencyCd',
    'BOLLCBMRC',
    'BOLLCBPartnerNm',
    'BOLLCBStateIndia',
    'BOLLCBTax',
    'IMPGcode',
    'InternetCurrencyCd',
    'InternetMRC',
    'InternetOTC',
    'InternetPartnerContractStartDt',
    'InternetPartnerContractTerm',
    'LLC_Partner_Name',
    'LLC_Partner_Ref',
    'Model',
    'OLLCAdminFee',
    'OLLCAPartnerContractStartDt',
    'OLLCAPartnerContractTerm',
    'OLLCAStateIndia',
    'OLLCATax',
    'OLLCBPartnerContractStartDt',
    'OLLCCurrencyCd',
    'OLLCMRC',
    'OLLCOTC',
    'OLLCPartnerContractStartDt',
    'OLLCPartnerContractTerm',
    'OLLCPartnerNm',
    'OLLCPPNo',
    'OLLCTax',
    'OriginState',
    'PartnerCctRef',
    'PartnerNm',
    'PortCurrencyCd',
    'PortMRC',
    'PortOTC',
    'PortPartnerContractStartDt',
    'PortPartnerContractTerm',
    'PortTax',
    'STIntSvcNo',
    'STPoNo',
    'SvcNo',
    'TermCarr',
    'InterCoReq',
    'business_sector',
    'exchange_code_a',
    'exchange_code_b',
    'brn',
    'am_contact',
    'am_id',
    'am_id_second',
    'sde_received_date',
    'arbor_service',
    'service_type',
    'order_priority',
    'crd_amendment_date',
    'old_crd',
    'new_crd',
    'crd_amendment_reason',
    'crd_amendment_reason_gsp',
    'OLLC Order Ack',
    'OLLC Site Survey',
    'FOC Date Received',
    'LLC Accepted by Singtel'
    # speed
    # ord_action_type
    # a-end address
    # b-end address
    # accountno - TBD
    # A-end-Cust
    # AAM
    # AM
    # B-end-Cust
    # Project Manager
    # Reseller
    # Techincal-Cust
    # Appt ID - TBD
    # Appt Group ID - TBD
]
