DATE_COLUMNS = [
    'CRD',
    'PreConfig_ActDueDate',
    'PreConfig_COM_Date',
    'Coordination_ActDueDate',
    'Coordination_COM_Date'
]

FINAL_COLUMNS = [
    'OrderCode',
    'ServiceNumber',
    'Customer',
    'OrderType',
    'OrderStatus',
    'TakenDate',
    'CurrentCRD',
    'InitialCRD',
    'CRDAmendmentDate',
    'CRDAmendmentReason',
    'Assignee',
    'ProjectCode',
    'CircuitTie',
    'ProductCode',
    'ProductDescription',
    'BusinessSector',
    'ExchangeCode_A',
    'ExchangeCode_B',
    'BRN',
    'SDEReceivedDate',
    'ArborService',
    'ServiceType',
    'OrderPriority',
    'ED_PD_Diversity',
    'Department',
    'GroupID',
    'ActStepNo',
    'ActivityName',
    'ActDueDate',
    'ActStatus',
    'ActReadyDate',
    'ActComDate',
    'ActDelayReasonDate',
    'ActDelayReason'
]

CRD_AMENDMENT_COLUMNS = [
    'OrderCode',
    'ServiceNumber',
    'Customer',
    'OrderType',
    'OrderStatus',
    'TakenDate',
    'CurrentCRD',
    'InitialCRD',
    'CRDAmendmentDate',
    'CRDAmendmentReason',
]
