version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  consoleFormat:
    format: "%(asctime)s - %(module)s - %(levelname)s - %(message)s"
    datefmt: "%T"
  fileFormat:
    format: "%(asctime)s - %(module)s - %(levelname)s - %(message)s"
    datefmt: "%F %a %T"
handlers:
  console:
    class: logging.StreamHandler
    # level: INFO
    formatter: consoleFormat
    stream: ext://sys.stdout
  timedRotatingFile:
    class: logging.handlers.TimedRotatingFileHandler
    # level: INFO
    formatter: fileFormat
    filename: "logs/report.log"
    when: "D"
    interval: 1
root:
  level: INFO
  handlers: [console, timedRotatingFile]
